spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/plus
    username: root
    password: ghks9430
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # 또는 create, create-drop, validate 중 선택
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
jwt:
  secret:
    key: BvdCDROpy/QRNPizw10GXalXzl41f/YOK2SfJNK2s+w=